<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="14727" started-at="2020-06-26T14:01:42Z" finished-at="2020-06-26T14:01:57Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="14727" started-at="2020-06-26T14:01:42Z" finished-at="2020-06-26T14:01:57Z">
      <class name="com.DemoProject.TestCases.test">
        <test-method status="PASS" signature="StatusReport()[pri:0, instance:com.DemoProject.TestCases.test@29ca901e]" name="StatusReport" is-config="true" duration-ms="405" started-at="2020-06-26T14:01:42Z" finished-at="2020-06-26T14:01:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- StatusReport -->
        <test-method status="PASS" signature="startSession()[pri:0, instance:com.DemoProject.TestCases.test@29ca901e]" name="startSession" is-config="true" duration-ms="14627" started-at="2020-06-26T14:01:42Z" finished-at="2020-06-26T14:01:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startSession -->
        <test-method status="FAIL" signature="loginWIthAdmin()[pri:0, instance:com.DemoProject.TestCases.test@29ca901e]" name="loginWIthAdmin" duration-ms="20" started-at="2020-06-26T14:01:57Z" finished-at="2020-06-26T14:01:57Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.reflect.InvocationTargetException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:131)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:63)
at com.DemoProject.TestCases.test.loginWIthAdmin(test.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:126)
... 27 more
Caused by: java.lang.NullPointerException
at com.DemoProject.Pages.LoginPage.<init>(LoginPage.java:16)
... 32 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWIthAdmin -->
        <test-method status="FAIL" signature="TearDownReport(org.testng.ITestResult)[pri:0, instance:com.DemoProject.TestCases.test@29ca901e]" name="TearDownReport" is-config="true" duration-ms="17" started-at="2020-06-26T14:01:57Z" finished-at="2020-06-26T14:01:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginWIthAdmin status=FAILURE method=test.loginWIthAdmin()[pri:0, instance:com.DemoProject.TestCases.test@29ca901e] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at helper.utility.Screenshoot(utility.java:64)
at com.DemoProject.Pages.BaseClass.TearDownReport(BaseClass.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDownReport -->
        <test-method status="SKIP" signature="EndSession()[pri:0, instance:com.DemoProject.TestCases.test@29ca901e]" name="EndSession" is-config="true" duration-ms="0" started-at="2020-06-26T14:01:57Z" finished-at="2020-06-26T14:01:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EndSession -->
      </class> <!-- com.DemoProject.TestCases.test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
